### ISSUE TITLE
Application fails with "Can't find custom attr constructor image"

### ISSUE THREAD

**Issue by BennyM** [raspberry-sharp/raspberry-sharp-io#57]
I'm trying to run a mono app on Rasbian Jessie Lite and receive the following error. I think I'm missing a dependency but am not sure what to install.

```
pi@raspberrypi:~/myapp $ mono MyApp.exe
Can't find custom attr constructor image: /home/pi/MyApp/Raspberry.IO.GeneralPurpose.dll mtoken: 0x0a000014
Unhandled loader error: 8, (null) System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (null)
* Assertion: should not be reached at loader.c:298

Stacktrace:


Native stacktrace:


Debug info from gdb:

[New LWP 887]
[New LWP 886]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
0x76e30ee8 in __libc_waitpid (pid=888, stat_loc=0x7ef2b14c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
40      ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id         Frame
  3    Thread 0x763ff430 (LWP 886) "mono" 0x76e2c7a4 in __pthread_cond_wait (cond=0x235420, mutex=0x235408) at pthread_cond_wait.c:187
  2    Thread 0x76a4b430 (LWP 887) "Finalizer" 0x76e2ea40 in do_futex_wait (isem=isem@entry=0x22a58c) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
* 1    Thread 0x76f27000 (LWP 882) "mono" 0x76e30ee8 in __libc_waitpid (pid=888, stat_loc=0x7ef2b14c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40

Thread 3 (Thread 0x763ff430 (LWP 886)):
#0  0x76e2c7a4 in __pthread_cond_wait (cond=0x235420, mutex=0x235408) at pthread_cond_wait.c:187
#1  0x001468a8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0x76a4b430 (LWP 887)):
#0  0x76e2ea40 in do_futex_wait (isem=isem@entry=0x22a58c) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
#1  0x76e2eaf4 in __new_sem_wait (sem=0x22a58c) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:69
#2  0x0015f164 in mono_sem_wait ()
#3  0x0010d90c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0x76f27000 (LWP 882)):
#0  0x76e30ee8 in __libc_waitpid (pid=888, stat_loc=0x7ef2b14c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
#1  0x0007a328 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

Aborted
```

**Comment by BennyM** [comment]
Compiled everything locally and updated one more package (core) and got it running.
